### ISSUE TITLE
ERROR 1049 (42000): Unknown database 'sunrays'

### ISSUE THREAD

**Issue by swaroopgokhale** [sunilkumargupta/MenuApp#3]
D:\TEMP\sunil_menuapp\MenuApp>"C:\Program Files\wamp\bin\mysql\mysql5.5.8\bin\mysql" -u root -p sunRays
Enter password: ****
ERROR 1049 (42000): Unknown database 'sunrays'

**Comment by sunilkumargupta** [comment]
Try this for the first time.
1. mysql -u root -p  <Enter>
2. CREATE DATABASE sunRays  <Enter>
3. connect sunRays; <Enter>
